### PR TITLE
Add nano + vim editors and add shell colors

### PR DESCRIPTION
**Pull request by tdgroot**
Add missing features to `warden shell`!

With the colorls.sh file, the following features are added:
* `alias ll='ls -l --color=auto' 2>/dev/null`
* `alias l.='ls -d .* --color=auto' 2>/dev/null`
* `alias ls='ls --color=auto' 2>/dev/null`
* Colored output
image

The `colorls.sh`, `DIR_COLORS` and `DIR_COLORS.lightbgcolor` files were copied from my Fedora 34 environment.

### CODE REVIEW

**Comment by tdgroot** [comment]
This is a follow up of davidalger/docker-images-php#7.

**Comment by navarr** [comment]
+1 to nano inclusion

**Comment by davidalger** [comment]
@tdgroot Love the inclusion of the colorls stuff, but given these files are typically installed via coreutils, I took the liberty to remove the copied files and instead added `coreutils-common` to the list of installed packages. Thanks for the enhancements, and apologies for the long delay on getting them merged.

**Comment by tdgroot** [comment]
> @tdgroot Love the inclusion of the colorls stuff, but given these files are typically installed via coreutils, I took the liberty to remove the copied files and instead added `coreutils-common` to the list of installed packages. Thanks for the enhancements, and apologies for the long delay on getting them merged.

Great, thanks for merging :). I didn't know that these specific files are installed through `coreutils-common`, interesting!

**Pull request merged**
