### PR TITLE
Arm64/develop (multi-platform builds for most images)

### PR DESCRIPTION
**Pull request by davidalger**
Updates the following image builds to support amd64 and arm64 architectures:

- Elasticsearch
  - Build for 6.13 has been dropped as ES 6.13 has reached EOL, will not receive any further path updates from vendor who does not plan to release arm64 binaries for this version of Elasticsearch
  - Builds now automatically build latest patch release of Elasticsearch images when executed
  - All current versions (i.e. 7.10 through 8.1) are now included in build matrix
- MailHog
- MariaDB
  - MariaDB versions 10.6 and 10.7 are now included in build matrix
- MySQL
  - Dropped builds for MySQL 5.6 and 5.7 as no Arm64 images for these exist
  - MySQL 8.0 image is now using the Oracle Linux base image as both community and Oracle maintained MySQL images only offer arm64 base images when using the Oracle Linux base OS
- Nginx
  - Nginx versions 1.19, 1.20 and 1.21 are now included in build matrix
- RabbitMQ
  - Version 3.9 now included in build matrix
- Redis
  - Version 6.2 now included in build matrix
- Varnish
  - Removes builds for versions 4.1 and 6.4 both of which are EOL and thus have no Arm64 binaries
  - Varnish 6.0 LTS, 6.5, and 6.6 remain with 7.0 images now included in build matrix

Huge shout out to both @ihor-sviziev, @drpayyne and others for the pioneering work foundational to these updates coming to fruition. Directly includes contents of open PRs #484, #488

### CODE REVIEW

**Comment by drpayyne** [comment]
So glad to see this. Thank you so much @davidalger! Appreciate your time and effort on this. 💯

**Comment by dudzio12** [comment]
When should we expect new release? :)

**Comment by ihor-sviziev** [comment]
Great job @davidalger 🎉! Thank you so much!

PS: here is a typo in first part of upgrade instruction:
```bash
warden svc pull
warden svc up --force-recreate # ensure mailhog is running native image
```

**Comment by Den4ik** [comment]
Good job 🚀

**Comment by Den4ik** [comment]
@davidalger Do you have any ideas and estimates for php images?

**Comment by davidalger** [comment]
> When should we expect new release? :)

@dudzio12 No new release needed to use these since existing versions of Warden will pull and use the arm64 images, just need to:

a) Update svc containers:

```sh
warden svc pull
warden svc up --force-recreate # ensure mailhog is running native image
```

b) Update env containers:

```sh
warden env pull
warden env up --force-recreate # ensure all containers are running native on arm64 where available
```

> @davidalger Do you have any ideas and estimates for php images?

@Den4ik I have ideas w/r/t php images, but no estimates (family, day job, other commitments, etc) since I do this in my spare time. Switching to Debian based images as has been done with @drpayyne's fork is a breaking change and will require a lot of care. First step though is updating the build process to use the Github actions that support multi-arch builds (and this is already in progress)

**Comment by ihor-sviziev** [comment]
> I have ideas w/r/t php images, but no estimates (family, day job, other commitments, etc) since I do this in my spare time.

@davidalger could you share your ideas on it, maybe we can send you a PR?

**Pull request merged**
