### PR TITLE
Docker compose v2

### PR DESCRIPTION
**Pull request by alinalexandru**
#423 Export variables without default value

I am using this fix, and everything seems to work.

### CODE REVIEW

**Comment by pchoate-trellis** [comment]
@alinalexandru Just tested this locally and it works perfectly. Thanks!

**Comment by pchoate-trellis** [comment]
I've been using this change locally for about a week now, but just noticed that the `COMPOSER_VERSION` variable in .env isn't forwarded to the PHP-FPM yml when it is compiled. I'm not entirely certain where/why that is yet.

**Comment by alinalexandru** [comment]
Notised that more variables are not forwarded. I'll investigate

**Comment by ihor-sviziev** [comment]
Looks like this issue isn't reproducing anymore in the `Docker Compose version v2.2.1`

**Comment by ihor-sviziev** [comment]
It worked perfectly fine with the latest docker-compose version for a few weeks.
I think we can close this PR as the issue was fixed on the docker-compose level

**Comment by davidalger** [comment]
Closing, as the issue was a BC break in an upstream dependency.

**Pull request closed without merging**
