### PR TITLE
Add Wordpress nginx config

### PR DESCRIPTION
**Pull request by tdgroot**
I was working on a Wordpress multisite and found that assets were not being loaded. Hence, I added a Wordpress specific nginx config file and loaded it up.

Tested this by running the following commands:

```shell
# In warden directory
images/scripts/build.sh nginx

# In warden development environment directory
warden env up
```

### CODE REVIEW

**Comment by tdgroot** [comment]
@davidalger if you need any more information or need help with testing, please let me know!

**Comment by tdgroot** [comment]
I'd really like this change to be included, now I constantly have to rebuild the nginx images to make my Wordpress multi sites work properly.

**Comment by tdgroot** [comment]
@davidalger I removed the `x-warden-nginx-template` headers, because they basically were added for debugging purposes and I had the feeling that the added headers were a change that needed your attention before merging.

Just wanted to make the PR a bit less complicated.

**Comment by GrimLink** [comment]
Thumbs up on this PR, it would be very useful @davidalger

**Comment by tdgroot** [comment]
Closing this PR, we started creating project specific `application.conf` files.

**Comment by sajidunnar** [comment]
Hello  , how we can extend the application.conf ?  I have same issue but but not sure how to this 

any link ?

**Pull request closed without merging**
