### PR TITLE
Modified ElasticHQ service to be optional

### PR DESCRIPTION
**Pull request by drpayyne**
#### MODIFIED

-  ElasticHQ service to be optional and enabled by default. 

### NOTES

Earlier, ElasticHQ was always on and I personally never use it. So I think this can be made optional, so that I can switch it off using the Warden configuration. I hope this would help other developers too.

### CODE REVIEW

**Comment by drpayyne** [comment]
Also, @davidalger - is this repo participating in Hacktoberfest? If yes, could you please add the appropriate label to this PR? 

https://hacktoberfest.digitalocean.com/resources/maintainers

**Comment by drpayyne** [comment]
Yep. Still relevant. :)

**Comment by ihor-sviziev** [comment]
@davidalger could you please just merge it? 😃

**Comment by ihor-sviziev** [comment]
@davidalger, could you please merge this PR as it improves behavior on ARM machines as the elasticsearch-hq image isn't available for ARM.
Also, the elasticsearch-hq project isn't maintained anymore

**Pull request closed without merging**
